controller_frequency: 20
xy_goal_tolerance: 0.05
yaw_goal_tolerance : 0.05
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.08
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  sim_time: 2.0