global_frame: map
robot_base_frame: base_link
update_frequency: 1
publish_frequency: 1
always_send_full_costmap: true
resolution: 0.05
transform_tolerance: 0.5

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  map_topic: /map
  subscribe_to_updates: true

obstacle_layer:
  observation_sources: bumpers lightsensors
  track_unknown_space: true
  publish_voxel_map: true
  bumpers: { data_type: PointCloud, topic: /bumpers, marking: true, observation_persistence: 10 }
  lightsensors: { data_type: PointCloud, topic: /lightsensors, marking: true, clearing: true }

inflation_layer:
  inflation_radius: 0.19
  cost_scaling_factor: 2.58
