local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  always_send_full_costmap: true
  resolution: 0.04
  rolling_window: true
  width: 3
  height: 3
  transform_tolerance: 0.5

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: /map
    subscribe_to_updates: true

  obstacle_layer:
    observation_sources: scan bumpers lightsensors
    track_unknown_space: true
    publish_voxel_map: true
    scan: { data_type: LaserScan, topic: /scan, marking: true, clearing: true }
    bumpers: { data_type: PointCloud, topic: /bumpers, marking: true, observation_persistence: 10 }
    lightsensors: { data_type: PointCloud, topic: /lightsensors, marking: true, clearing: true }

  inflation_layer:
    inflation_radius: 0.17